name: Benchmark CI
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  REPO_NAME: 'stats-holder'
  PROCCESSOR_REPO_NAME: ${{ github.event.repository.name }}
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: echo vars
        run: |
            echo "${{ github.event.sender.email }}"
            echo "${{ github.event.repository.owner.email }}"
            echo "${{ github.event.repository.name }}"
      - name: bench data
        run: |
          git clone https://user:$GITHUB_TOKEN@github.com/${{ github.repository_owner }}/${{ env.REPO_NAME }}
          cd ${{ env.REPO_NAME }}
          git config user.name "cshezi"
          git config user.email "cshezi@sybrin.co.za"
      - name: Switch to temp branch
        run: |
          cd ${{ env.REPO_NAME }}
          git checkout temp-holder
          git pull
          cat "${{ env.PROCCESSOR_REPO_NAME }}".csv >> "${{ env.PROCCESSOR_REPO_NAME }}".csv.tmp
          git add "${{ env.PROCCESSOR_REPO_NAME }}".csv.tmp
          git stash
          git checkout main
          git stash apply
      - name: Write data
        run: |
          cd ${{ env.REPO_NAME }}
          cat "${{ env.PROCCESSOR_REPO_NAME }}".csv.tmp >> "${{ env.PROCCESSOR_REPO_NAME }}".csv
          git reset "${{ env.PROCCESSOR_REPO_NAME }}".csv.tmp
          git add "${{ env.PROCCESSOR_REPO_NAME }}".csv
          git commit -m "${{ github.event.number}} Pushed update of ${{ env.PROCCESSOR_REPO_NAME }}"
      - name: push data
        run: |
          cd ${{ env.REPO_NAME }}
          git push origin main
